//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaireTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaireTip()
        {
            this.Emlaks = new HashSet<Emlak>();
        }
    
        public int DaireTipID { get; set; }
        public string Adi { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emlak> Emlaks { get; set; }
    }
}
