//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emlak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emlak()
        {
            this.EmlakFotoes = new HashSet<EmlakFoto>();
            this.EmlakOzelliks = new HashSet<EmlakOzellik>();
            this.Portfoys = new HashSet<Portfoy>();
        }
    
        public int EmlakID { get; set; }
        public int KatNumarasi { get; set; }
        public string DaireNo { get; set; }
        public int BrutMetrekare { get; set; }
        public int NetMetrekare { get; set; }
        public int BanyoSayisi { get; set; }
        public double PiyasaBedeli { get; set; }
        public double KiraBedeli { get; set; }
        public double Aidat { get; set; }
        public int BinaYasi { get; set; }
        public int KatSayisi { get; set; }
        public string Cephe { get; set; }
        public string IsinmaSekli { get; set; }
        public bool Otopark { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> Adresi_AdresID { get; set; }
        public Nullable<int> Dairetipi_DaireTipID { get; set; }
        public Nullable<int> Durumu_KonutDurumID { get; set; }
        public Nullable<int> Sahibi_MusteriID { get; set; }
        public Nullable<int> Turu_TurID { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual DaireTip DaireTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmlakFoto> EmlakFotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmlakOzellik> EmlakOzelliks { get; set; }
        public virtual KonutDurum KonutDurum { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Tur Tur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfoy> Portfoys { get; set; }
    }
}
