//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozlesme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sozlesme()
        {
            this.OdemePlans = new HashSet<OdemePlan>();
        }
    
        public int SozlesmeID { get; set; }
        public System.DateTime SozlesmeTarihi { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> KiraSozlesmesi_KiraSozlesmeID { get; set; }
        public Nullable<int> Musterisi_MusteriID { get; set; }
        public Nullable<int> OdemePlan_OdemePlanID { get; set; }
        public Nullable<int> OdemePlani_OdemePlanID { get; set; }
        public Nullable<int> Portfoyu_PortfoyID { get; set; }
        public Nullable<int> SatisSozlesmesi_SatisSozlesmeID { get; set; }
    
        public virtual KiraSozlesme KiraSozlesme { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemePlan> OdemePlans { get; set; }
        public virtual OdemePlan OdemePlan { get; set; }
        public virtual OdemePlan OdemePlan1 { get; set; }
        public virtual Portfoy Portfoy { get; set; }
        public virtual SatisSozlesme SatisSozlesme { get; set; }
    }
}
