//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmlakOzellik : BaseEntity
    {
        public int ID { get; set; }
        public bool AcikBalkon { get; set; }
        public bool CelikKapi { get; set; }
        public bool DolaplıMutfak { get; set; }
        public bool Dusakabin { get; set; }
        public bool FransizBalkon { get; set; }
        public bool KapaliBalkon { get; set; }
        public bool Kartonpiyer { get; set; }
        public bool Laminant { get; set; }
        public bool OcakDogalgazi { get; set; }
        public bool SeramikZemin { get; set; }
        public bool SicakSu { get; set; }
        public bool Asansor { get; set; }
        public bool GuneyCepheli { get; set; }
        public bool Hidrafor { get; set; }
        public bool IsiYalitimi { get; set; }
        public bool CaddeyeYakin { get; set; }
        public bool Dolmus { get; set; }
        public bool OkulaYakin { get; set; }
        public Nullable<int> Emlak_EmlakID { get; set; }
    
        public virtual Emlak Emlak { get; set; }
    }
}
