//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmlakFoto : BaseEntity
    {
        public int ID { get; set; }
        public string KucukFotoYol { get; set; }
        public string BuyukFotoYol { get; set; }
        public string KapakFotoYol { get; set; }
        public Nullable<int> Emlak_EmlakID { get; set; }
    
        public virtual Emlak Emlak { get; set; }
    }
}
