//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriLike : BaseEntity
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> EmlakId { get; set; }
    
        public virtual Emlak Emlak { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
