//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Emlaks = new HashSet<Emlak>();
            this.Portfoys = new HashSet<Portfoy>();
            this.Sozlesmes = new HashSet<Sozlesme>();
            this.MusteriLikes = new HashSet<MusteriLike>();
        }
    
        public int MusteriID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int TC { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public Nullable<int> Adresi_AdresID { get; set; }
        public Nullable<int> Personel_PersonelID { get; set; }
    
        public virtual Adre Adre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emlak> Emlaks { get; set; }
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfoy> Portfoys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme> Sozlesmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriLike> MusteriLikes { get; set; }
    }
}
