//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemePlan : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OdemePlan()
        {
            this.Sozlesmes = new HashSet<Sozlesme>();
            this.Sozlesmes1 = new HashSet<Sozlesme>();
        }
    
        public int OdemePlanID { get; set; }
        public int TaksitSayisi { get; set; }
        public int ToplamOdeme { get; set; }
        public Nullable<int> Sozlesme_SozlesmeID { get; set; }
    
        public virtual Sozlesme Sozlesme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme> Sozlesmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme> Sozlesmes1 { get; set; }
    }
}
