//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider : BaseEntity
    {
        public int ID { get; set; }
        public string PATH { get; set; }
        public int PRIORTY { get; set; }
        public string PLACE { get; set; }
    }
}
